//
//  ClipboardManager.swift
//  FunNotch
//
//  Keeps a short history of what you have copied, so the notch can hand it
//  back. Entries marked concealed (password managers) or transient are skipped,
//  following the org.nspasteboard convention.
//

import AppKit
import Combine
import SwiftUI

struct ClipboardEntry: Identifiable, Equatable {
    enum Payload: Equatable {
        case text(String)
        case image(NSImage)
        case files([URL])
    }

    let id: UUID
    let payload: Payload
    let copiedAt: Date
    /// Name of the app that put it there, when we could tell.
    let sourceApp: String?
    /// Pinned entries stay put and survive the history limit.
    var isPinned: Bool = false

    var isText: Bool {
        if case .text = payload { return true }
        return false
    }

    /// One-line description for the tile.
    var preview: String {
        switch payload {
        case let .text(value):
            let trimmed = value.trimmingCharacters(in: .whitespacesAndNewlines)
            return trimmed.replacingOccurrences(of: "\n", with: " ")
        case .image:
            return "Image"
        case let .files(urls):
            return urls.count == 1
                ? urls[0].lastPathComponent
                : "\(urls.count) files"
        }
    }

    var symbol: String {
        switch payload {
        case let .text(value):
            if value.hasPrefix("http://") || value.hasPrefix("https://") { return "link" }
            return "text.alignleft"
        case .image: return "photo"
        case .files: return "doc"
        }
    }

    static func == (lhs: ClipboardEntry, rhs: ClipboardEntry) -> Bool {
        lhs.id == rhs.id
    }
}

@MainActor
final class ClipboardManager: ObservableObject {
    static let shared = ClipboardManager()

    @Published private(set) var entries: [ClipboardEntry] = []

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    /// Change count of writes we made ourselves, so pasting back does not
    /// re-record the same thing.
    private var ownChangeCount = -1
    private var cancellables = Set<AnyCancellable>()

    private let storageKey = "clipboardTextHistory"

    private static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    private init() {
        restore()
    }

    func start() {
        NotificationCenter.default.publisher(for: .settingsChanged)
            .compactMap { $0.object as? String }
            .filter { $0 == "clipboardHistoryEnabled" }
            .receive(on: RunLoop.main)
            .sink { [weak self] _ in self?.restartPolling() }
            .store(in: &cancellables)

        restartPolling()
    }

    private func restartPolling() {
        timer?.invalidate()
        timer = nil
        guard Settings.shared.clipboardHistoryEnabled else { return }

        lastChangeCount = NSPasteboard.general.changeCount
        let timer = Timer(timeInterval: 0.6, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // Skip our own writes, and anything a password manager marked private.
        guard pasteboard.changeCount != ownChangeCount else { return }
        let types = Set(pasteboard.types ?? [])
        guard types.isDisjoint(with: [Self.concealedType, Self.transientType, Self.autoGeneratedType]) else {
            return
        }

        let source = NSWorkspace.shared.frontmostApplication?.localizedName

        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !urls.isEmpty {
            record(.files(urls), source: source)
            return
        }

        if let text = pasteboard.string(forType: .string),
           !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            record(.text(text), source: source)
            return
        }

        if let images = pasteboard.readObjects(forClasses: [NSImage.self], options: nil) as? [NSImage],
           let image = images.first {
            record(.image(image), source: source)
        }
    }

    private func record(_ payload: ClipboardEntry.Payload, source: String?) {
        // Copying the same thing twice should move it up, not duplicate it.
        if let index = entries.firstIndex(where: { $0.payload == payload }) {
            let existing = entries.remove(at: index)
            entries.insert(
                ClipboardEntry(id: existing.id, payload: payload, copiedAt: Date(), sourceApp: source),
                at: 0
            )
        } else {
            entries.insert(
                ClipboardEntry(id: UUID(), payload: payload, copiedAt: Date(), sourceApp: source),
                at: 0
            )
        }

        // Pinned entries do not count against the limit and are never dropped.
        let limit = max(Settings.shared.clipboardHistoryLimit, 1)
        var unpinned = entries.filter { !$0.isPinned }
        if unpinned.count > limit {
            let doomed = Set(unpinned.suffix(unpinned.count - limit).map(\.id))
            entries.removeAll { doomed.contains($0.id) }
            unpinned = entries.filter { !$0.isPinned }
        }

        persist()
    }

    /// Puts an entry back on the pasteboard.
    func copyBack(_ entry: ClipboardEntry) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()

        switch entry.payload {
        case let .text(value):
            pasteboard.setString(value, forType: .string)
        case let .image(image):
            pasteboard.writeObjects([image])
        case let .files(urls):
            pasteboard.writeObjects(urls as [NSURL])
        }

        ownChangeCount = pasteboard.changeCount
        lastChangeCount = pasteboard.changeCount
    }

    /// Moves a copied file or image onto the shelf.
    @discardableResult
    func sendToShelf(_ entry: ClipboardEntry) -> Bool {
        switch entry.payload {
        case let .files(urls):
            return urls.reduce(false) { ShelfManager.shared.add(url: $1) || $0 }
        case let .image(image):
            guard let tiff = image.tiffRepresentation,
                  let bitmap = NSBitmapImageRep(data: tiff),
                  let png = bitmap.representation(using: .png, properties: [:])
            else { return false }
            return ShelfManager.shared.addTemporary(
                data: png,
                preferredName: "Clipboard Image \(ShelfManager.timestampSuffix()).png"
            )
        case let .text(value):
            guard let data = value.data(using: .utf8) else { return false }
            return ShelfManager.shared.addTemporary(
                data: data,
                preferredName: "Clipboard Text \(ShelfManager.timestampSuffix()).txt"
            )
        }
    }

    /// Fills the history with fixed entries, for snapshots.
    func injectPreviewEntries(_ payloads: [(ClipboardEntry.Payload, String?)]) {
        entries = payloads.enumerated().map { index, item in
            ClipboardEntry(
                id: UUID(),
                payload: item.0,
                copiedAt: Date(),
                sourceApp: item.1,
                isPinned: index == 0
            )
        }
    }

    func togglePin(_ entry: ClipboardEntry) {
        guard let index = entries.firstIndex(where: { $0.id == entry.id }) else { return }
        entries[index].isPinned.toggle()
        // Pinned things belong at the front where they are easy to reach.
        let updated = entries.remove(at: index)
        if updated.isPinned {
            entries.insert(updated, at: 0)
        } else {
            let firstUnpinned = entries.firstIndex { !$0.isPinned } ?? entries.count
            entries.insert(updated, at: firstUnpinned)
        }
        persistPinned()
        persist()
    }

    /// Entries matching a search, pinned first.
    func filtered(by query: String) -> [ClipboardEntry] {
        let trimmed = query.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        let matches = trimmed.isEmpty
            ? entries
            : entries.filter { $0.preview.lowercased().contains(trimmed) }
        return matches.sorted { lhs, rhs in
            if lhs.isPinned != rhs.isPinned { return lhs.isPinned }
            return lhs.copiedAt > rhs.copiedAt
        }
    }

    private func persistPinned() {
        let pinned = entries.filter(\.isPinned).compactMap { entry -> String? in
            guard case let .text(value) = entry.payload else { return nil }
            return value
        }
        Settings.shared.clipboardPinned = pinned
    }

    func remove(_ entry: ClipboardEntry) {
        entries.removeAll { $0.id == entry.id }
        persist()
    }

    /// Clears everything except pinned entries.
    func clear() {
        entries.removeAll { !$0.isPinned }
        persist()
    }

    // MARK: - Persistence
    //
    // Only text survives a relaunch: images would bloat the preferences, and
    // copied files may have moved by then.

    private func persist() {
        let texts = entries.compactMap { entry -> String? in
            guard case let .text(value) = entry.payload else { return nil }
            return value
        }
        UserDefaults.standard.set(Array(texts.prefix(50)), forKey: storageKey)
    }

    private func restore() {
        let pinned = Set(Settings.shared.clipboardPinned)
        guard let texts = UserDefaults.standard.stringArray(forKey: storageKey) else { return }
        entries = texts.map {
            ClipboardEntry(
                id: UUID(),
                payload: .text($0),
                copiedAt: .distantPast,
                sourceApp: nil,
                isPinned: pinned.contains($0)
            )
        }
    }
}
